# source: https://strapi.io/documentation/3.0.0-beta.x/installation/docker.html
version: '3'

services:
  strapi:
    container_name: strapi
    image: strapi/strapi:3.1.4-alpine
    ports:
      - 1337:1337
    volumes:
      - strapi-volume:/srv/app